# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025-Present Datadog, Inc.

# Air configuration for Sticker Award service
root = "."
tmp_dir = "tmp"

[build]
  # Build command with disabled optimisations for easier debugging
  cmd = "go build -gcflags=all=-N ./cmd/server"
  bin = "server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", ".git"]
  delay = 200  # milliseconds between changes 