version: '3.8'

services:
  # PostgreSQL database for sticker-award service
  sticker-award-db:
    image: postgres:16
    container_name: sticker-award-db
    environment:
      POSTGRES_DB: sticker_award
      POSTGRES_USER: sticker_user
      POSTGRES_PASSWORD: sticker_password
    ports:
      - "5432:5432"
    volumes:
      - sticker-award-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sticker_user -d sticker_award"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL database for user-management service
  user-management-db:
    image: postgres:16
    container_name: user-management-db
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: user_mgmt_user
      POSTGRES_PASSWORD: user_mgmt_password
    ports:
      - "5433:5432"  # Map to different port on host to avoid conflict
    volumes:
      - user-management-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_mgmt_user -d user_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Sticker Award Service
  # http://localhost:8080/health
  # http://localhost:8080/api/award/v1/users/user-001/stickers
  sticker-award:
    build:
      context: ./sticker-award
      dockerfile: src/main/docker/Dockerfile.jvmlocal
    container_name: sticker-award
    depends_on:
      sticker-award-db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://sticker-award-db:5432/sticker_award
      QUARKUS_DATASOURCE_USERNAME: sticker_user
      QUARKUS_DATASOURCE_PASSWORD: sticker_password
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_DEVSERVICES_ENABLED: "false"
    ports:
      - "8080:8080"

  # User Management Service
  user-management:
    build:
      context: ./user-management
      dockerfile: src/Stickerlandia.UserManagement.AspNet/Dockerfile
    container_name: user-management
    depends_on:
      user-management-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DRIVING: ASPNET
      DRIVEN: AGNOSTIC
      messaging: "YOUR KAFKA BOOTSTRAP SERVERS"
      database: "Host=user-management-db;Port=5432;Database=user_management;Username=user_mgmt_user;Password=user_mgmt_password"

    ports:
      - "8081:80"  # Map to 8081 on host to avoid conflict with other services

volumes:
  sticker-award-data:
  user-management-data:
