openapi: 3.0.4
info:
  title: Sticker Award Service
  version: v1
  description: Service for managing sticker assignments to users
paths:
  /api/awards/v1/assignments/{userId}:
    get:
      tags:
        - StickerAssignments
      description: Get stickers assigned to a user (access controlled based on caller identity)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user whose stickers to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStickersResponse'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    post:
      tags:
        - StickerAssignments
      description: Assign a new sticker to a user (access controlled based on caller identity)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user to assign the sticker to
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignStickerCommand'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StickerAssignmentResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/awards/v1/assignments/{userId}/{stickerId}:
    delete:
      tags:
        - StickerAssignments
      description: Remove a sticker assignment from a user (access controlled based on caller identity)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user to remove the sticker from
        - name: stickerId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the sticker to remove
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StickerRemovalResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /health:
    get:
      tags:
        - Health
      description: Check service health
      responses:
        '200':
          description: Service is healthy

components:
  schemas:
    AssignStickerCommand:
      type: object
      properties:
        stickerId:
          type: string
          nullable: false
        reason:
          type: string
          nullable: true
      required:
        - stickerId
      additionalProperties: false

    StickerAssignmentDTO:
      type: object
      properties:
        stickerId:
          type: string
          nullable: false
        assignedAt:
          type: string
          format: date-time
        reason:
          type: string
          nullable: true
      additionalProperties: false
      description: Award assignment data - only contains assignment info with sticker reference

    UserStickersResponse:
      type: object
      properties:
        userId:
          type: string
          nullable: false
        stickers:
          type: array
          items:
            $ref: '#/components/schemas/StickerAssignmentDTO'
      additionalProperties: false

    StickerAssignmentResponse:
      type: object
      properties:
        userId:
          type: string
          nullable: false
        stickerId:
          type: string
          nullable: false
        assignedAt:
          type: string
          format: date-time
      additionalProperties: false

    StickerRemovalResponse:
      type: object
      properties:
        userId:
          type: string
          nullable: false
        stickerId:
          type: string
          nullable: false
        removedAt:
          type: string
          format: date-time
      additionalProperties: false

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}