# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025-Present Datadog, Inc.

name: 'Setup CDK'
description: 'Sets up AWS CDK and installs shared constructs'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  aws-role-arn:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'eu-west-1'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install CDK
      shell: bash
      run: npm install -g aws-cdk

    - name: Install shared constructs
      shell: bash
      run: |
        cd shared/lib/shared-constructs
        npm i

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ inputs.aws-region }}

    - name: Set Commit Hash Environment Variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "sha_full=$(git rev-parse "$GITHUB_SHA")" >> "$GITHUB_ENV"
