name: TEMPORARY AWS Push Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "user-management/**"
      - ".github/**"
  workflow_dispatch:

env:
  REGISTRY: 772954894450.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_NAME_USER_SERVICE: stickerlandia-user-management
  ECR_REPOSITORY_URL: 772954894450.dkr.ecr.eu-west-1.amazonaws.com/stickerlandia-user-management

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get Commit Info
        id: get_sha
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-1"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: "772954894450"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_USER_SERVICE }}
          tags: |
            latest
            ${{ env.COMMIT_SHA }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.IMAGE_NAME_USER_SERVICE }}
          IMAGE_TAG: "latest"
        run: |
          docker build "./user-management" -f "./user-management/src/Stickerlandia.UserManagement.Api/Dockerfile" -t stickerlandia-user-management
          docker tag stickerlandia-user-management:latest 772954894450.dkr.ecr.eu-west-1.amazonaws.com/stickerlandia-user-management:latest
          docker push 772954894450.dkr.ecr.eu-west-1.amazonaws.com/stickerlandia-user-management:latest
