name: User Management Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Run Unit Tests
        shell: bash
        run: |
          cd user-management/tests/Stickerlandia.UserManagement.UnitTest
          dotnet test

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    strategy:
      matrix:
        run_as:
          - ASPNET
          - AZURE_FUNCTIONS
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      # Pulling the base images in a seperate test ensures the Aspire startup time is not affected by the time it takes to pull the images
      - name: Pull Base Images
        shell: bash
        run: |
          docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
          docker pull mcr.microsoft.com/azure-messaging/servicebus-emulator:1.0.1
          docker pull mcr.microsoft.com/azure-sql-edge:latest
      - name: Run Integration Tests
        shell: bash
        env:
          RUN_AS: ${{ matrix.run_as }}
        run: |
          cd user-management/tests/Stickerlandia.UserManagement.IntegrationTest && dotnet test --logger:"console;verbosity=detailed"
      - name: View test output
        if: always()
        shell: bash
        run: |
          cd user-management/tests/Stickerlandia.UserManagement.IntegrationTest
          cat testoutput.txt